import {Card} from "../components/ui/Card.jsx";
import {IconCircle} from "../components/ui/IconCircle.jsx";
import {Bell, BellOff} from "lucide-react";
import T from "../theme.js";
import {Toggle} from "../components/ui/Toggle.jsx";
import {secondaryBtn} from "../styles/shared.js";
import React from "react";

export function SettingsTab({muted, onToggleMute, onReset}) {
    return (
        <div style={{display: "flex", flexDirection: "column", gap: 12}}>
            <Card style={{display: "flex", justifyContent: "space-between", alignItems: "center"}}>
                <div style={{display: "flex", gap: 12, alignItems: "center"}}>
                    <IconCircle>{muted ? <BellOff size={18}/> : <Bell size={18}/>}</IconCircle>
                    <div>
                        <p style={{margin: 0, fontSize: 14, color: T.textPrimary, fontWeight: 500}}>Nudges</p>
                        <p style={{margin: "2px 0 0", fontSize: 12, color: T.textSecondary}}>Research-based patterns
                            from your own data</p>
                    </div>
                </div>
                <Toggle checked={!muted} onChange={() => onToggleMute()}/>
            </Card>

            <Card>
                <p style={{margin: "0 0 4px", fontSize: 14, color: T.textPrimary, fontWeight: 500}}>About this
                    prototype</p>
                <p style={{margin: 0, fontSize: 13, color: T.textSecondary, lineHeight: 1.6}}>
                    Data is stored locally to this app and never leaves your device. Insights are generated by a small
                    rules
                    engine that checks your logs against published behavior-change findings — nothing here is medical or
                    coaching advice.
                </p>
            </Card>

            <button onClick={onReset} style={{...secondaryBtn, color: "#E58A8A"}}>
                Reset all data
            </button>
        </div>
    );
}